// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK53eI0bBHIUjxjhV0RMP68VKnYtKS69E',
    appId: '1:273148589810:web:e8ff08970755b5c06a826b',
    messagingSenderId: '273148589810',
    projectId: 'ecom-21bb9',
    authDomain: 'ecom-21bb9.firebaseapp.com',
    storageBucket: 'ecom-21bb9.appspot.com',
    measurementId: 'G-GBSRPH4YYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBilAgfCFYHm1l2ZegpJJXeNENKeuBRIso',
    appId: '1:273148589810:android:0efd0357d17372706a826b',
    messagingSenderId: '273148589810',
    projectId: 'ecom-21bb9',
    storageBucket: 'ecom-21bb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBhHvQywZoq8uytb36bMKUUlIqj1xKDx8',
    appId: '1:273148589810:ios:59da89cab64bfc626a826b',
    messagingSenderId: '273148589810',
    projectId: 'ecom-21bb9',
    storageBucket: 'ecom-21bb9.appspot.com',
    iosClientId: '273148589810-3913a4tg6o5a1uua48skg9en202va3qj.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecomapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBhHvQywZoq8uytb36bMKUUlIqj1xKDx8',
    appId: '1:273148589810:ios:59da89cab64bfc626a826b',
    messagingSenderId: '273148589810',
    projectId: 'ecom-21bb9',
    storageBucket: 'ecom-21bb9.appspot.com',
    iosClientId: '273148589810-3913a4tg6o5a1uua48skg9en202va3qj.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecomapp',
  );
}
